// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vectorstore} from '../models';

export function GenerateAnswer(arg1:string,arg2:number):Promise<string>;

export function IndexFiles(arg1:Array<string>):Promise<void>;

export function IndexFolder(arg1:string):Promise<void>;

export function InitEngine(arg1:main.EngineConfig):Promise<void>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function Search(arg1:string,arg2:number):Promise<Array<vectorstore.SearchResult>>;

export function SelectFolder():Promise<string>;

export function StoreSize():Promise<number>;
